# Generated by Django 6.1 on 2026-08-26 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('all_day', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='#6366F1', max_length=32)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('faith', 'Faith'), ('health', 'Health'), ('study', 'Study'), ('social', 'Social'), ('other', 'Other')], default='personal', max_length=32)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', models.JSONField(blank=True, null=True)),
                ('exception_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('recurring_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.calendarevent')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
