# Generated by Django 6.1 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='default_view',
            field=models.CharField(default='list', max_length=20),
        ),
    ]
