# Generated by Django 6.1 on 2026-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_attachments_task_due_time_task_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
