# Generated by Django 6.1 on 2026-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_in_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(blank=True, default='#F59E0B', max_length=32),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_amount',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_unit',
            field=models.CharField(default='times', max_length=50),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='completed_amount',
            field=models.FloatField(default=1.0),
        ),
    ]
