# Generated by Django 6.1 on 2026-08-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_habit_color_habit_frequency_habit_frequency_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
