# Generated by Django 6.1 on 2026-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_habit_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='focussession',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktag',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
