# Generated by Django 6.1 on 2026-08-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_calendarevent_in_trash_focussession_in_trash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(blank=True, default='personal', max_length=64),
        ),
    ]
