# Generated by Django 6.1 on 2026-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_calendarevent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
