# Generated by Django 6.1 on 2026-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_avatar_profile_bio_profile_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
