# Generated by Django 6.1 on 2026-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_db_indexes_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calculation_method',
            field=models.CharField(blank=True, default='MWL', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Tunis', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Tunisia', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, default='dark', max_length=20),
        ),
    ]
