# Generated by Django 6.1 on 2026-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_calculation_method_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='accent_color',
            field=models.CharField(blank=True, default='#10B981', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='color',
            field=models.CharField(blank=True, default='#10B981', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktag',
            name='color',
            field=models.CharField(blank=True, default='#10B981', max_length=32),
        ),
    ]
