# Generated by Django 6.1 on 2026-10-02 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], db_index=True, default='pomodoro', max_length=20)),
                ('duration', models.IntegerField(default=1500, help_text='Duration completed in seconds')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('interrupted', 'Interrupted')], db_index=True, default='completed', max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text='Custom session label or title if not linked to a specific task', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_focus_sessions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Focus Session',
                'verbose_name_plural': 'Focus Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
