# Generated by Django 6.1 on 2026-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhkar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('morning', 'Morning (أذكار الصباح)'), ('evening', 'Evening (أذكار المساء)'), ('sleep', 'Sleep & Waking (النوم والاستيقاظ)'), ('food', 'Food & Drink (الطعام والشراب)'), ('travel', 'Travel (السفر)'), ('distress', 'Distress & Relief (الكرب والهم)'), ('mosque', 'Mosque (المسجد)'), ('parents', 'Parents & Family (الوالدين)'), ('forgiveness', 'Forgiveness & Repentance (الاستغفار)'), ('general', "General Du'a (أدعية عامة)")], db_index=True, default='morning', help_text="Category of Dhikr or Du'a", max_length=32)),
                ('arabic_text', models.TextField(help_text='Arabic text of the Dhikr with diacritics / tashkeel')),
                ('translation', models.TextField(blank=True, default='', help_text='English meaning and translation')),
                ('transliteration', models.TextField(blank=True, default='', help_text='Phonetic transliteration in Latin script')),
                ('target_count', models.PositiveIntegerField(default=1, help_text='Recommended repetition count (e.g. 1, 3, 33, 100)')),
                ('source', models.CharField(blank=True, default='', help_text='Hadith or Quran reference (e.g. Sahih al-Bukhari, Abu Dawood)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ascending display order within the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adhkar',
                'verbose_name_plural': 'Adhkar',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoodDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Arabic title of the good deed (e.g. صيام, صدقة, قراءة القرآن)', max_length=100)),
                ('title_en', models.CharField(help_text='English title of the good deed (e.g. Fasting, Sadaqah, Read Quran)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Virtue, Hadith reference, or practical guideline for this deed')),
                ('emoji', models.CharField(blank=True, default='🤲', help_text='Emoji icon representing the deed', max_length=16)),
                ('is_recommended_excuse', models.BooleanField(default=False, help_text='Recommended alternative deed during excuse / menstruation mode')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order on the daily checklist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Good Deed',
                'verbose_name_plural': 'Good Deeds',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Arabic text of the Hadith')),
                ('translation', models.TextField(blank=True, default='', help_text='English translation of the narration')),
                ('narrator', models.CharField(blank=True, default='', help_text='Companion narrator (e.g. Umar ibn al-Khattab, Abu Hurairah)', max_length=150)),
                ('source', models.CharField(help_text='Source compilation (e.g. Sahih al-Bukhari, Sahih Muslim, Al-Tirmidhi)', max_length=255)),
                ('category', models.CharField(db_index=True, help_text='Thematic topic (e.g. Iman, Akhlaq, Ilm, Ibadah, Sadaqah, Rahmah)', max_length=64)),
                ('grade', models.CharField(choices=[('sahih', 'Sahih (صحيح)'), ('hasan', 'Hasan (حسن)'), ('hasan_sahih', 'Hasan Sahih (حسن صحيح)'), ('muttafaqun_alayh', "Muttafaqun 'Alayh (متفق عليه)")], default='sahih', help_text='Authenticity classification', max_length=32)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority / ordering index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hadith',
                'verbose_name_plural': 'Hadiths',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
