# Generated by Django 6.1 on 2026-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_db_indexes_beta'),
        ('faith', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhatmahLog',
            fields=[
            ],
            options={
                'verbose_name': 'Khatmah Log',
                'verbose_name_plural': 'Khatmah Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.khatmah',),
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
            ],
            options={
                'verbose_name': 'Prayer Log',
                'verbose_name_plural': 'Prayer Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.prayerlog',),
        ),
        migrations.AddField(
            model_name='adhkar',
            name='category_en',
            field=models.CharField(blank=True, help_text='English name of the category', max_length=100, null=True),
        ),
    ]
