# Generated by Django 6.1 on 2026-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='accent_color',
            field=models.CharField(blank=True, default='#10B981', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='#10B981', max_length=32),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='default_view',
            field=models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban'), ('timeline', 'Timeline')], default='list', max_length=20),
        ),
    ]
