# Generated by Django 6.1 on 2026-10-04 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='system_code',
            field=models.CharField(blank=True, db_index=True, help_text="System identifier for automated sync (e.g. 'morning_adhkar', 'evening_adhkar', 'quran')", max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), ('system_code__isnull', False)), fields=('owner', 'system_code'), name='unique_owner_system_habit'),
        ),
    ]
